author: Alex Rupérez
author_url: https://twitter.com/alexruperez
clean: true
copyright: Copyright (c) 2020 Alex Rupérez
github_file_prefix: https://github.com/alexruperez/CryptoKitCLI/blob/master
github_url: https://github.com/alexruperez/CryptoKitCLI
module: CryptoKitCLI
root_url: https://alexruperez.github.io/CryptoKitCLI
sourcekitten_sourcefile:
  - docs/CryptoKitCLI.json
theme: fullwidth
